const data = {
	products: [
		{
			name: "Free Shirt",
			category: "Shirts",
			image: "/images/shirt1.jpeg",
			price: 70,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: "A popular shirt",
			slug: "free-shirt",
		},
		{
			name: "Fit Shirt",
			category: "Shirts",
			image: "/images/shirt2.jpeg",
			price: 35,
			brand: "Adidas",
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: "A popular shirt",
			slug: "fit-shirt",
		},
		{
			name: "Slim Shirt",
			category: "Shirts",
			image: "/images/shirt3.jpeg",
			price: 45,
			brand: "Lacoste",
			rating: 4.5,
			numReviews: 10,
			countInStock: 10,
			description: "A popular shirt",
			slug: "slim-shirt",
		},
		{
			name: "Golf Pants",
			category: "Pants",
			image: "/images/pants1.jpeg",
			price: 70,
			brand: "Nike",
			rating: 4.5,
			numReviews: 10,
			countInStock: 20,
			description: "A popular pants model",
			slug: "golf-pants",
		},
		{
			name: "Classic Pants",
			category: "Pants",
			image: "/images/pants2.jpeg",
			price: 49.99,
			brand: "Armani",
			rating: 4.6,
			numReviews: 11,
			countInStock: 5,
			description: "Classic pants for all ocasions",
			slug: "classic-pants",
		},
		{
			name: "Loose Pants",
			category: "Pants",
			image: "/images/pants3.jpeg",
			price: 32.9,
			brand: "Troy",
			rating: 4.9,
			numReviews: 4,
			countInStock: 1,
			description: "Ideal home pants, very comfortable",
			slug: "loose-pants",
		},
	],
};

export default data;
